### ISSUE TITLE
could not find package openpay_plugin at https://pub.dartlang.org

### ISSUE THREAD

**Issue by hecuervo** [Jairolaya12x/openpay_plugin#7]
hi, you can post your plugin on flutter to be able to use it.

thanks a lot

**Comment by Jairolaya12x** [comment]
Hi, I'll post soon.

For the moment you can use adding this in your pubspec.yaml

``` yaml
openpay_plugin:
    git:
      url: https://github.com/Jairolaya12x/openpay_plugin.git
```

Kind regards 🤘
